/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_txznet_txz_module_vad_TXZWebRTCVad */

#ifndef _Included_com_txznet_txz_module_vad_TXZWebRTCVad
#define _Included_com_txznet_txz_module_vad_TXZWebRTCVad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_txznet_txz_module_vad_TXZWebRTCVad
 * Method:    splitPCM
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_txznet_txz_module_vad_TXZWebRTCVad_splitPCM
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
